# Generated by Django 4.0a1 on 2021-11-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('cou_se_id', models.AutoField(primary_key=True, serialize=False)),
                ('cou_info', models.CharField(max_length=250)),
                ('cou_type', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='stu',
            fields=[
                ('stu_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('opend_id', models.CharField(max_length=30)),
                ('wsex', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='tea',
            fields=[
                ('tea_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('opend_id', models.CharField(max_length=30)),
                ('wsex', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='wuser_info',
            fields=[
                ('opend_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('role', models.CharField(default='0', max_length=20)),
                ('res_time', models.DateField()),
                ('wsex', models.CharField(max_length=2)),
            ],
        ),
    ]
