# Generated by Django 4.0a1 on 2021-11-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courese_selected',
            fields=[
                ('cou_se_id', models.AutoField(primary_key=True, serialize=False)),
                ('cou_id', models.CharField(max_length=20)),
                ('stu_id', models.CharField(max_length=20)),
                ('tea_id', models.CharField(max_length=20)),
                ('ai_scoure_one', models.IntegerField(max_length=3)),
                ('scoure_one', models.CharField(max_length=30)),
            ],
        ),
    ]
