# Generated by Django 4.0a1 on 2021-11-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_courese_selected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stu',
        ),
        migrations.DeleteModel(
            name='tea',
        ),
        migrations.RemoveField(
            model_name='wuser_info',
            name='role',
        ),
        migrations.AddField(
            model_name='wuser_info',
            name='invitation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wuser_info',
            name='is_stud',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='wuser_info',
            name='wsex',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
