# Generated by Django 4.0a1 on 2021-11-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_delete_stu_delete_tea_remove_wuser_info_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wuser_info',
            name='is_stud',
            field=models.BooleanField(default='True'),
        ),
    ]
