# Generated by Django 4.0a1 on 2021-11-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_wuser_info_is_stud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cou_se_id',
            new_name='course_id',
        ),
    ]
