# Generated by Django 4.0a1 on 2021-11-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_rename_cou_se_id_course_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courese_selected',
            name='stu_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='courese_selected',
            name='tea_id',
            field=models.CharField(max_length=30),
        ),
    ]
