# Generated by Django 4.0a1 on 2021-11-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_courese_selected_stu_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wuser_info',
            name='invitation',
        ),
        migrations.AddField(
            model_name='courese_selected',
            name='invitation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='courese_selected',
            name='stu_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='courese_selected',
            name='tea_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
