# Generated by Django 4.0a1 on 2021-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_wuser_info_invitation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stu',
            fields=[
                ('stu_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('wsex', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tea',
            fields=[
                ('tea_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('wsex', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='courese_selected',
            name='invitation',
        ),
        migrations.RemoveField(
            model_name='wuser_info',
            name='is_stud',
        ),
        migrations.AddField(
            model_name='wuser_info',
            name='role',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='courese_selected',
            name='ai_scoure_one',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='courese_selected',
            name='cou_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='cou_type',
            field=models.CharField(max_length=1),
        ),
    ]
