# Generated by Django 4.0a1 on 2021-11-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_stu_tea_remove_courese_selected_invitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wuser_info',
            name='name',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
