# Generated by Django 4.0a1 on 2021-11-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_courese_selected_ai_scoure_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_score',
            fields=[
                ('cou_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('stud_id', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('real_score', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='stu',
        ),
        migrations.DeleteModel(
            name='tea',
        ),
    ]
