# Generated by Django 4.0a1 on 2021-11-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_course_score_delete_stu_delete_tea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course_score',
        ),
    ]
