# Generated by Django 4.0a1 on 2021-11-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_delete_course_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_score',
            fields=[
                ('score_id', models.AutoField(default='1', primary_key=True, serialize=False)),
                ('cou_id', models.CharField(max_length=30)),
                ('stud_id', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('real_score', models.IntegerField()),
            ],
        ),
    ]
