# Generated by Django 4.0a1 on 2021-11-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_course_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courese_selected',
            name='ai_scoure_one',
        ),
        migrations.RemoveField(
            model_name='courese_selected',
            name='scoure_one',
        ),
    ]
