# Generated by Django 4.0a1 on 2021-11-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_course_score_evaluate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='frist_rule',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='frist_rule_weight',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='second_rule',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='second_rule_weight',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
