# Generated by Django 4.0a1 on 2021-11-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_course_frist_rule_course_frist_rule_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ai_score_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lujing', models.CharField(default='', max_length=25)),
                ('fluency_score', models.FloatField()),
                ('phone_score', models.FloatField()),
                ('total_score', models.FloatField()),
                ('integrity_score', models.CharField(default='', max_length=15)),
                ('tone_score', models.FloatField()),
                ('content', models.CharField(default='', max_length=300)),
                ('is_rejected', models.BooleanField()),
            ],
        ),
    ]
