# Generated by Django 4.0a1 on 2021-11-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_alter_ai_score_storage_integrity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_score_storage',
            name='integrity_score',
            field=models.FloatField(),
        ),
    ]
