# Generated by Django 4.0a1 on 2021-11-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_alter_ai_score_storage_integrity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_score_storage',
            name='lujing',
            field=models.CharField(default='', max_length=60),
        ),
    ]
